name: Consumer Deployment

on:
  push:
    branches:
      - develop
      - release

jobs:

  enterprise-validation:

    uses: ramtruely/salesforce-enterprise-poc/.github/workflows/deploy.yml@feature/pr-validation-poc

    with:
      target_env: ${{ github.base_ref == 'develop' && 'TEST' || 'LOAD' }}

    secrets: inherit