name: Consumer Deployment

on:
  pull_request:
    branches:
      - develop
      - release

jobs:

  enterprise-validation:
    uses: ramtruely/salesforce-enterprise-poc/.github/workflows/deploy.yml@feature/pr-validation-poc

    secrets: inherit