# Consumer Validation
name: Consumer PR Validation

on:
  pull_request:
    branches:
      - develop
      - release

jobs:

  enterprise-validation:

    uses: ramtruely/salesforce-enterprise-poc/.github/workflows/pr-validation.yml@feature/pr-validation-poc

    with:
      target_env: ${{ github.base_ref == 'develop' && 'TEST' || 'LOAD' }}

    secrets: inherit